### ISSUE TITLE
窗口尺寸变化的时候，标尺的宽高并未跟随

### ISSUE THREAD

**Issue by devie2020** [LvHuaiSheng/leafer-x-ruler#1]
![image](https://github.com/LvHuaiSheng/leafer-x-ruler/assets/33315229/a4d78175-e6b3-48e7-9f7b-158316bb87fd)

**Comment by LvHuaiSheng** [comment]
> ![image](https://private-user-images.githubusercontent.com/33315229/308044894-a4d78175-e6b3-48e7-9f7b-158316bb87fd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDkwMTkwNjMsIm5iZiI6MTcwOTAxODc2MywicGF0aCI6Ii8zMzMxNTIyOS8zMDgwNDQ4OTQtYTRkNzgxNzUtZTZiMy00OGU3LTlmN2ItMTU4MzE2YmI4N2ZkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjI3VDA3MjYwM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWYzNzA0NTUzODdlZDMxMWUyMjkyMWRjNjRkN2UzMzYwODc0NTk1MjJmMmI5ZDI2NjVkZWQyMzQ4NTQxMmZmNWMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.FVxH3NYLBMqR6Odt1tzpkt_CjlxTiZRfAfrOw8xj5P4)

需要触发一下leafer-ui的resize事件，如果是在vue项目中参考下面的使用方式：
```
// 窗口监听
const viewport = ref<HTMLElement>() // 画布view
useResizeObserver(viewport, entries => {
  const [ entry ] = entries
  const { width, height } = entry.contentRect
  console.log('窗口变化前', leaferUi.app.width, leaferUi.app.height)
  leaferUi.app.resize({ width, height })
  setTimeout(()=>{
    // 重新渲染标尺
    ruler.forceRender()
  },0)
  console.log('窗口变化后', leaferUi.app.width, leaferUi.app.height)
})
```
