### ISSUE TITLE
卡尺高度超出屏幕后 如何让垂直卡尺出现跟随画布的滚动条，拖动画布垂直卡尺跟随滚动

### ISSUE THREAD

**Issue by wzjiscode** [LvHuaiSheng/leafer-x-ruler#10]
卡尺高度超出屏幕后 如何让垂直卡尺出现跟随画布的滚动条，拖动画布垂直卡尺跟随滚动

https://github.com/user-attachments/assets/72ff9942-ea5d-41ff-8d62-d67bda52c302

**Comment by wzjiscode** [comment]
补充：建议大佬建一个群方便沟通

**Comment by wzjiscode** [comment]
new Ruler 如何挂载到sky层

**Comment by LvHuaiSheng** [comment]
> 卡尺高度超出屏幕后 如何让垂直卡尺出现跟随画布的滚动条，拖动画布垂直卡尺跟随滚动

视频中这种效果目前是可以实现的，像浏览器这种单独的滚动条估计要看下leafer的scroll插件，需要自己适配实现一下

> 补充：建议大佬建一个群方便沟通

现在插件用的人数不多 暂不考虑单独建插件群，如果需要的话可以加我微信LHS11177 拉你进gzm-design的交流群

> new Ruler 如何挂载到sky层

想挂载到sky层可以修改下插件的代码，使用sky层进行标尺的渲染
