### ISSUE TITLE
画布缩放尺子没有变化

### ISSUE THREAD

**Issue by wumingluren** [LvHuaiSheng/leafer-x-ruler#2]
演示站是好的，但是我抄的演示这块的代码缩放画布尺子不动。
不知道这个代码跟演示站是否一致呢？
https://github.com/LvHuaiSheng/leafer-x-ruler/blob/master/playground/src/App.vue

**Comment by LvHuaiSheng** [comment]
> 演示站是好的，但是我抄的演示这块的代码缩放画布尺子不动。 不知道这个代码跟演示站是否一致呢？ https://github.com/LvHuaiSheng/leafer-x-ruler/blob/master/playground/src/App.vue

查查看一下RenderEvent.AFTER事件触发是否正常，标尺接收的参数需要传入最顶层的app 并不是App.app，传入其它的是无效的

**Comment by wumingluren** [comment]
> > 演示站是好的，但是我抄的演示这块的代码缩放画布尺子不动。 不知道这个代码跟演示站是否一致呢？ https://github.com/LvHuaiSheng/leafer-x-ruler/blob/master/playground/src/App.vue
> 
> 查查看一下RenderEvent.AFTER事件触发是否正常，标尺接收的参数需要传入最顶层的app 并不是App.app，传入其它的是无效的

ruler.enabled = false
后面找到问题了，是有一行禁用。
