### ISSUE TITLE
画布改变标尺没有自动改变

### ISSUE THREAD

**Issue by wumingluren** [LvHuaiSheng/leafer-x-ruler#3]
通过缩放浏览器窗口来改变画布大小
使用了这个代码的，但是还是得在画布上点击一下才会更新标尺。
```
useResizeObserver(divRef, (entries) => {
        const [entry] = entries
        const { width, height } = entry.contentRect
        // 这步是为了触发leafer-ui的resize事件，标尺在监听到resize事件后会重新渲染
        leafer.app.resize({ width, height })
      })
```

**Comment by wumingluren** [comment]
![image](https://github.com/LvHuaiSheng/leafer-x-ruler/assets/41581133/45a644a8-ec0b-4bb7-b464-426cf9d58d21)
演示站也是一样的

**Comment by LvHuaiSheng** [comment]
收到，我复测一下问题

---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 发送日期 | 2024年04月16日 17:15 |
| 收件人 | LvHuaiSheng/leafer-x-ruler ***@***.***> |
| 抄送人 | Subscribed ***@***.***> |
| 主题 | Re: [LvHuaiSheng/leafer-x-ruler] 画布改变标尺没有自动改变 (Issue #3) |

image.png (view on web)
演示站也是一样的

**Comment by LvHuaiSheng** [comment]
> 通过缩放浏览器窗口来改变画布大小 使用了这个代码的，但是还是得在画布上点击一下才会更新标尺。
> 
> ```
> useResizeObserver(divRef, (entries) => {
>         const [entry] = entries
>         const { width, height } = entry.contentRect
>         // 这步是为了触发leafer-ui的resize事件，标尺在监听到resize事件后会重新渲染
>         leafer.app.resize({ width, height })
>       })
> ```

npm新发了一个1.0.8版本，解决了这个问题 同时依赖也更新到了leafer最新版本，可以到体验站试用一下看看

**Comment by wumingluren** [comment]
> > 通过缩放浏览器窗口来改变画布大小 使用了这个代码的，但是还是得在画布上点击一下才会更新标尺。
> > ```
> > useResizeObserver(divRef, (entries) => {
> >         const [entry] = entries
> >         const { width, height } = entry.contentRect
> >         // 这步是为了触发leafer-ui的resize事件，标尺在监听到resize事件后会重新渲染
> >         leafer.app.resize({ width, height })
> >       })
> > ```
> 
> npm新发了一个1.0.8版本，解决了这个问题 同时依赖也更新到了leafer最新版本，可以到体验站试用一下看看

本来还想看下依赖更新到了哪个leafer版本，才发现代码没提交。

**Comment by LvHuaiSheng** [comment]
leafer更新到21版本了，代码稍晚会我提交一下


---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 发送日期 | 2024年04月19日 11:59 |
| 收件人 | LvHuaiSheng/leafer-x-ruler ***@***.***> |
| 抄送人 | LvHuaiSheng ***@***.***>,
Comment ***@***.***> |
| 主题 | Re: [LvHuaiSheng/leafer-x-ruler] 画布改变标尺没有自动改变 (Issue #3) |

通过缩放浏览器窗口来改变画布大小 使用了这个代码的，但是还是得在画布上点击一下才会更新标尺。

useResizeObserver(divRef, (entries) => {
        const [entry] = entries
        const { width, height } = entry.contentRect
        // 这步是为了触发leafer-ui的resize事件，标尺在监听到resize事件后会重新渲染
        leafer.app.resize({ width, height })
      })


npm新发了一个1.0.8版本，解决了这个问题 同时依赖也更新到了leafer最新版本，可以到体验站试用一下看看

本来还想看下依赖更新到了哪个leafer版本，才发现代码没提交。
