### ISSUE TITLE
支持更多长度单位？

### ISSUE THREAD

**Issue by jingguanzhang** [LvHuaiSheng/leafer-x-ruler#4]
现在貌似只支持px单位，但在实际的生产环境中，更多时候使用需要cm/mm这类单位，未来版本是否有支持计划

**Comment by LvHuaiSheng** [comment]
@jingguanzhang 有一条标准的单位转换库就可以支持，如果有类似的开源库或你们内部实现可开源的代码可以推荐一下~

**Comment by jingguanzhang** [comment]
> @jingguanzhang 有一条标准的单位转换库就可以支持，如果有类似的开源库或你们内部实现可开源的代码可以推荐一下~

谢谢，chatgpt已经帮我改好了

**Comment by wzjiscode** [comment]
> > @jingguanzhang 有一条标准的单位转换库就可以支持，如果有类似的开源库或你们内部实现可开源的代码可以推荐一下~
> 
> 谢谢，chatgpt已经帮我改好了

怎么改的大佬
