### ISSUE TITLE
长度单位修改，将px改为mm如何修改源码?

### ISSUE THREAD

**Issue by wzjiscode** [LvHuaiSheng/leafer-x-ruler#6]
问题：vue3 + ts 项目如何修改源码
1. 在哪个文件夹下修改
2. 在哪个方法下修改
3. 如何修改
4. 修改后如何调用

**Comment by LvHuaiSheng** [comment]
代码在[Ruler.ts](https://github.com/LvHuaiSheng/leafer-x-ruler/blob/master/src/Ruler.ts)中，
可以定义一个标准的单位转换方法，然后调整里面的刻度间距和单位文字，
修改完后直接把Ruler.ts拷贝到自己项目中 把原有的`import { Ruler } from 'leafer-x-ruler'` 改成 `import { Ruler } from '“Ruler.ts文件的地址”' `使用即可

**Comment by wzjiscode** [comment]
> 代码在[Ruler.ts](https://github.com/LvHuaiSheng/leafer-x-ruler/blob/master/src/Ruler.ts)中， 可以定义一个标准的单位转换方法，然后调整里面的刻度间距和单位文字， 修改完后直接把Ruler.ts拷贝到自己项目中 把原有的`import { Ruler } from 'leafer-x-ruler'` 改成 `import { Ruler } from '“Ruler.ts文件的地址”' `使用即可

感谢大佬指导

**Comment by wzjiscode** [comment]
> 代码在[Ruler.ts](https://github.com/LvHuaiSheng/leafer-x-ruler/blob/master/src/Ruler.ts)中， 可以定义一个标准的单位转换方法，然后调整里面的刻度间距和单位文字， 修改完后直接把Ruler.ts拷贝到自己项目中 把原有的`import { Ruler } from 'leafer-x-ruler'` 改成 `import { Ruler } from '“Ruler.ts文件的地址”' `使用即可

项目不使用ts的话如何修改源码

**Comment by LvHuaiSheng** [comment]
> > 代码在[Ruler.ts](https://github.com/LvHuaiSheng/leafer-x-ruler/blob/master/src/Ruler.ts)中， 可以定义一个标准的单位转换方法，然后调整里面的刻度间距和单位文字， 修改完后直接把Ruler.ts拷贝到自己项目中 把原有的`import { Ruler } from 'leafer-x-ruler'` 改成 `import { Ruler } from '“Ruler.ts文件的地址”' `使用即可
> 
> 项目不使用ts的话如何修改源码

可以打包一下 会编译出未压缩的js代码，也可以删掉全部类型，然后把后缀改成js即可
