### ISSUE TITLE
能不能提供一份转mm的代码大佬

### ISSUE THREAD

**Issue by wzjiscode** [LvHuaiSheng/leafer-x-ruler#8]
1. 实际场景是app应用编辑器，设置卡尺、设计打印模板，打印纸张的宽高是（100mm，70mm）
2. 卡尺总宽度（100mm平铺整个屏幕）使用屏幕宽度，然后接收一个宽高值（width: 100,height: 70, 单位mm），然后根据接收的宽高值计算mm刻度并平铺整个页面宽度。
3. 卡尺总高度使用接收的高度（70mm），然后根据宽度的mm占多少px，设置高度
4. 效果图看附件内容
![微信图片_20241210151041](https://github.com/user-attachments/assets/68b4b8f8-64f5-41ac-af88-9df55a198df6)
![微信图片_20241210151034](https://github.com/user-attachments/assets/64f99a80-9ccc-4815-b6cb-427d538cece6)

**Comment by LvHuaiSheng** [comment]
这个后面有时间了可以看下补充上多单位转换，近期暂时还不会增加；也欢迎进行PR~
