### ISSUE TITLE
0刻度位置被文本px遮盖问题

### ISSUE THREAD

**Issue by wzjiscode** [LvHuaiSheng/leafer-x-ruler#9]
![image](https://github.com/user-attachments/assets/7f049ae8-0dbd-4567-8c65-671a7dc1b0c7)
左上角坐标点0位置开始有误差如何调整源码
1. 左上角px文本显示后如何x,y轴继续从0开始，也就是不计算px文本占位空间

**Comment by LvHuaiSheng** [comment]
> ![image](https://private-user-images.githubusercontent.com/37691429/394545794-7f049ae8-0dbd-4567-8c65-671a7dc1b0c7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM4ODUxNzAsIm5iZiI6MTczMzg4NDg3MCwicGF0aCI6Ii8zNzY5MTQyOS8zOTQ1NDU3OTQtN2YwNDlhZTgtMGRiZC00NTY3LThjNjUtNjcxYTdkYzFiMGM3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjExVDAyNDExMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTYxYWI1MmZhNzBiMTRhOGFjOGE0MDUzZDI4NzNkOGRjMjA4MTZlYzgxMTQ2Njg3MGFhNmIwM2ExYWU1MzY3MTAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.C17FoBhkvs3WMR5oN8XefbUnw7jKkVFF1PJ0lNrmzsg) 左上角坐标点0位置开始有误差如何调整源码
> 
>     1. 左上角px文本显示后如何x,y轴继续从0开始，也就是不计算px文本占位空间

[这并不是误差，xy的起始点都是最左上角的0，标尺会覆盖在元素的上方是因为动态显隐会基于已有画布的位置来进行渲染，如果增加偏移就会超出画布区域，如果你们需要不覆盖元素可以在[Ruler.ts](https://github.com/LvHuaiSheng/leafer-x-ruler/blob/master/src/Ruler.ts) 进行调整 设置标尺位置的偏移距离来实现

**Comment by wzjiscode** [comment]
> > ![image](https://private-user-images.githubusercontent.com/37691429/394545794-7f049ae8-0dbd-4567-8c65-671a7dc1b0c7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM4ODUxNzAsIm5iZiI6MTczMzg4NDg3MCwicGF0aCI6Ii8zNzY5MTQyOS8zOTQ1NDU3OTQtN2YwNDlhZTgtMGRiZC00NTY3LThjNjUtNjcxYTdkYzFiMGM3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjExVDAyNDExMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTYxYWI1MmZhNzBiMTRhOGFjOGE0MDUzZDI4NzNkOGRjMjA4MTZlYzgxMTQ2Njg3MGFhNmIwM2ExYWU1MzY3MTAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.C17FoBhkvs3WMR5oN8XefbUnw7jKkVFF1PJ0lNrmzsg) 左上角坐标点0位置开始有误差如何调整源码
> > ```
> > 1. 左上角px文本显示后如何x,y轴继续从0开始，也就是不计算px文本占位空间
> > ```
> 
> [这并不是误差，xy的起始点都是最左上角的0，标尺会覆盖在元素的上方是因为动态显隐会基于已有画布的位置来进行渲染，如果增加偏移就会超出画布区域，如果你们需要不覆盖元素可以在[Ruler.ts](https://github.com/LvHuaiSheng/leafer-x-ruler/blob/master/src/Ruler.ts) 进行调整 设置标尺位置的偏移距离来实现

好的 感谢
